language: node_js

git:
  # Do not take whole history, but ensure to not break things:
  # - Merging multiple PR's around same time may introduce a case where it's not
  #   the last merge commit that is to be tested
  # - Aside of merge commit we need a previous commit to be able to detect a version switch
  depth: 10

branches:
  only:
    - master # Do not build PR branches
    - /^v\d+\.\d+\.\d+$/ # Ensure to build release tags

stages:
  - name: Test
  - name: Deploy
    if: tag =~ ^v\d+\.\d+\.\d+$

jobs:
  include:
    # In most cases it's best to configure one job per Platform & Node.js version combination
    # (job boot & setup takes ca 1 minute, one task run lasts ca few seconds)

    # PR's from branches
    # Ensure commit messages follow CC, and confirm on changelog in case of release PR's
    - name: 'Prettier check updated, Lint updated, Commitlint, Changelog confirm (on release) - Node.js v12'
      if: type = pull_request AND fork = false
      node_js: 12
      script:
        - |
          npm run prettier-check-updated && npm run lint-updated && npm run commitlint-ci-pull-request &&
          tagName=`git diff master package.json | grep '"version": "' | grep -oE "\d+\.\d+\.\d+"`
          if [ $? -eq 0 ]; then
            # If release PR, confirm we have a changelog
            npx dump-release-from-cc-changelog $tagName
          fi

    # PR's from forks
    # Do not validate commit messages,
    # (if user didn't ensure CC, PR should be squash merged with valid CC commit message)
    - name: 'Prettier check updated, Lint updated - Node.js v12'
      if: type = pull_request AND fork = true
      node_js: 12
      script: npm run prettier-check-updated && npm run lint-updated

    # master branch
    - name: 'Lint, Tag on version bump - Node.js v12'
      env: #TODO: Expose Github token at GITHUB_TOKEN
      if: branch = master AND type = push
      node_js: 12
      script:
        - |
          npm run lint &&
          # If package version was changed with last merged PR, push tag
          tagName=`git diff HEAD^ package.json | grep '"version": "' | grep -oE "\d+\.\d+\.\d+"`
          if [ $? -eq 0 ]; then
            git tag v$tagName && git push -q https://$GITHUB_TOKEN@github.com/serverless/eslint-config --tags
          fi

    # version tag
    - stage: Deploy
      env: #TODO: Expose Github token at GITHUB_TOKEN
      node_js: 12
      script: skip
      deploy:
        provider: npm
        email: services@serverless.com
        api_key:
          secure: EgoetjrRlGfvGnmVp8A0btr1CzB0hl7owVIpbfk4zXJzhGEbHoVu0CG0IdmyLN+JlaZa7EDJTjkDCd6g3fVAh9TT7ZCeaq8YwbZDrql7mAJj7xYQAyM4eSkc95BRzcFJBx7Mxr6H90IDLxKr6ZtB+HEdiHN+59XbepKYYJeb1jHfnKn5xzOqk4BdnZo6pKfudfeO+7/BwJJ0FwlFA40bY2HS/Lp+NG/2IedNR7k3m/5W83/XH5qlWP8jhBKlxrAzks27aNo+42xHkRCVyPViJKq0mfz1hl2bfswChWHgaCuajp+0amNL39pgIX9eXxFc3bNX9Iftox5t31elEhsw06vvuAaVkKEd+VEMaDySbQ9M+irKZeREg+NFYZLnc2WiEE3Sexo6hm9eM2q2KEZ7bleN9B0CQAut1XXLRQEts80rzss4Z2Q7AZb9cOYBQlj9Wf1X0Y74UqvnDn83a4Y38a+lhx7J2q691ZeM1UFSCdO0QfeJRkB55bSyHqUqrLAqUN7eNsKGdBH0kvYIGFREgGgReEpBRAuNqWuJ/5qexp63Kbf+09raG5IvfxSIM5fJ5KE5VxSduBdRnSH0GNKfjuq296/Rg4fmm/bygZ3Yk5L6Wd41SUU8uHzlZFBwtcvxAKDTQe6s+5JU24ilqxOx6J4Ut34X3dIbLLAmoB1ogdM=
      after_deploy: npx github-release-from-cc-changelog $TRAVIS_TAG
