language: node_js

git:
  # Do not take whole history, but ensure to not break things:
  # - Merging multiple PR's around same time may introduce scenario that it's not last merge commit
  #   that is to be tested, and we need to have access to it
  # - At least 2 last commits need to be provided to properly detect a version switch
  depth: 10

branches:
  only:
    - master # Do not build PR branches
    - /^v\d+\.\d+\.\d+$/ # Ensure to build release tags

stages:
  - name: Test

jobs:
  include:
    # In most cases it's best to configure one job per Platform & Node.js version combination
    # (job setup takes ca 1 minute, one task ca few seconds)

    # PR's from branches
    # Ensure commit messages follow CC
    - name: 'Prettier check updated, Lint updated, Commitlint - Node.js v12'
      if: type = pull_request AND fork = false
      node_js: 12
      script: npm run prettier-check-updated && npm run lint-updated && npm run commitlint-ci-pull-request

    # PR's from forks
    # Do not validate commit messages,
    # (if user didn't ensure CC, PR should be squash merged with valid CC commit message)
    - name: 'Prettier check updated, Lint updated - Node.js v12'
      if: type = pull_request AND fork = true
      node_js: 12
      script: npm run prettier-check-updated && npm run lint-updated

    # master branch and version tags
    - name: 'Lint - Node.js v12'
      if: type = push
      node_js: 12
      script: npm run lint
